In [1]:
import pandas as pd
import numpy as np

# Read all CSV files from 4 to 22 and concatenate them vertically
file_paths = [f"/work/spx_intraday_2014.xlsx - {i}.csv" for i in range(4, 23)]

# Read and concatenate
all_dataframes = [pd.read_csv(file) for file in file_paths]
SPX_2014_df = pd.concat(all_dataframes, ignore_index=True)

SPX_2014_df

                 Date     Open     High      Low    Close
0       5/31/19 16:10  2752.06  2752.06  2752.06  2752.06
1       5/31/19 16:05  2752.06  2752.06  2752.06  2752.06
2       5/31/19 16:00  2752.00  2752.07  2752.00  2752.06
3       5/31/19 15:55  2752.69  2753.63  2751.75  2751.75
4       5/31/19 15:50  2754.55  2755.44  2753.52  2753.52
...               ...      ...      ...      ...      ...
106211   3/11/14 9:50  1874.69  1874.80  1872.81  1874.19
106212   3/11/14 9:45  1876.58  1876.58  1874.42  1874.68
106213   3/11/14 9:40  1877.50  1878.25  1876.13  1876.62
106214   3/11/14 9:35  1878.92  1879.73  1877.07  1877.51
106215   3/11/14 9:30  1878.26  1879.69  1878.26  1879.01

[106216 rows x 5 columns]

In [2]:
SPX_2014_df = SPX_2014_df[~SPX_2014_df['Date'].str.contains('16:05|16:10|16:15')]
SPX_2014_df

                 Date     Open     High      Low    Close
2       5/31/19 16:00  2752.00  2752.07  2752.00  2752.06
3       5/31/19 15:55  2752.69  2753.63  2751.75  2751.75
4       5/31/19 15:50  2754.55  2755.44  2753.52  2753.52
5       5/31/19 15:45  2752.51  2755.41  2752.25  2754.84
6       5/31/19 15:40  2751.41  2752.87  2751.01  2752.57
...               ...      ...      ...      ...      ...
106211   3/11/14 9:50  1874.69  1874.80  1872.81  1874.19
106212   3/11/14 9:45  1876.58  1876.58  1874.42  1874.68
106213   3/11/14 9:40  1877.50  1878.25  1876.13  1876.62
106214   3/11/14 9:35  1878.92  1879.73  1877.07  1877.51
106215   3/11/14 9:30  1878.26  1879.69  1878.26  1879.01

[103606 rows x 5 columns]

In [3]:
# Convert 'Date' column to datetime for proper sorting
SPX_2014_df['Date'] = pd.to_datetime(SPX_2014_df['Date'], format='%m/%d/%y %H:%M')
# Sort the dataframe in chronological order
SPX_2014_df = SPX_2014_df.sort_values(by='Date')
SPX_2014_df

/tmp/ipykernel_3151/3414910839.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  SPX_2014_df['Date'] = pd.to_datetime(SPX_2014_df['Date'], format='%m/%d/%y %H:%M')

                      Date     Open     High      Low    Close
106215 2014-03-11 09:30:00  1878.26  1879.69  1878.26  1879.01
106214 2014-03-11 09:35:00  1878.92  1879.73  1877.07  1877.51
106213 2014-03-11 09:40:00  1877.50  1878.25  1876.13  1876.62
106212 2014-03-11 09:45:00  1876.58  1876.58  1874.42  1874.68
106211 2014-03-11 09:50:00  1874.69  1874.80  1872.81  1874.19
...                    ...      ...      ...      ...      ...
6      2019-05-31 15:40:00  2751.41  2752.87  2751.01  2752.57
5      2019-05-31 15:45:00  2752.51  2755.41  2752.25  2754.84
4      2019-05-31 15:50:00  2754.55  2755.44  2753.52  2753.52
3      2019-05-31 15:55:00  2752.69  2753.63  2751.75  2751.75
2      2019-05-31 16:00:00  2752.00  2752.07  2752.00  2752.06

[103606 rows x 5 columns]

In [4]:
SPX_2014_df = SPX_2014_df[['Date', 'Close']]
SPX_2014_df

                      Date    Close
106215 2014-03-11 09:30:00  1879.01
106214 2014-03-11 09:35:00  1877.51
106213 2014-03-11 09:40:00  1876.62
106212 2014-03-11 09:45:00  1874.68
106211 2014-03-11 09:50:00  1874.19
...                    ...      ...
6      2019-05-31 15:40:00  2752.57
5      2019-05-31 15:45:00  2754.84
4      2019-05-31 15:50:00  2753.52
3      2019-05-31 15:55:00  2751.75
2      2019-05-31 16:00:00  2752.06

[103606 rows x 2 columns]

In [5]:
import numpy as np
SPX_2014_df['ln(pt/pt-1)'] = np.log(SPX_2014_df['Close'] / SPX_2014_df['Close'].shift(1))
SPX_2014_df = SPX_2014_df.dropna()
SPX_2014_df = SPX_2014_df[~(SPX_2014_df['Date'].dt.time == pd.to_datetime("09:30").time())]
SPX_2014_df

/tmp/ipykernel_3151/224355107.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  SPX_2014_df['ln(pt/pt-1)'] = np.log(SPX_2014_df['Close'] / SPX_2014_df['Close'].shift(1))

                      Date    Close  ln(pt/pt-1)
106214 2014-03-11 09:35:00  1877.51    -0.000799
106213 2014-03-11 09:40:00  1876.62    -0.000474
106212 2014-03-11 09:45:00  1874.68    -0.001034
106211 2014-03-11 09:50:00  1874.19    -0.000261
106210 2014-03-11 09:55:00  1875.00     0.000432
...                    ...      ...          ...
6      2019-05-31 15:40:00  2752.57     0.000465
5      2019-05-31 15:45:00  2754.84     0.000824
4      2019-05-31 15:50:00  2753.52    -0.000479
3      2019-05-31 15:55:00  2751.75    -0.000643
2      2019-05-31 16:00:00  2752.06     0.000113

[102291 rows x 3 columns]

In [6]:
SPX_2014_df.set_index('Date', inplace=True)

In [7]:
intraday_2014 = pd.DataFrame(SPX_2014_df['ln(pt/pt-1)'])

In [8]:
intraday_2014.sort_index(inplace=True)

In [9]:
intraday_2014.to_csv("intraday_2014.csv", index=True)

In [10]:
SPX_2014_df["Date"] = SPX_2014_df.index

In [11]:
SPX_2014_df

                       Close  ln(pt/pt-1)                Date
Date
2014-03-11 09:35:00  1877.51    -0.000799 2014-03-11 09:35:00
2014-03-11 09:40:00  1876.62    -0.000474 2014-03-11 09:40:00
2014-03-11 09:45:00  1874.68    -0.001034 2014-03-11 09:45:00
2014-03-11 09:50:00  1874.19    -0.000261 2014-03-11 09:50:00
2014-03-11 09:55:00  1875.00     0.000432 2014-03-11 09:55:00
...                      ...          ...                 ...
2019-05-31 15:40:00  2752.57     0.000465 2019-05-31 15:40:00
2019-05-31 15:45:00  2754.84     0.000824 2019-05-31 15:45:00
2019-05-31 15:50:00  2753.52    -0.000479 2019-05-31 15:50:00
2019-05-31 15:55:00  2751.75    -0.000643 2019-05-31 15:55:00
2019-05-31 16:00:00  2752.06     0.000113 2019-05-31 16:00:00

[102291 rows x 3 columns]

In [12]:
# Resample SPX_close_df to daily frequency, summing up measurements, dividing by the number of measurements, and multiplying by 78
SPX_daily_2014_df = SPX_2014_df.resample('D', on='Date').apply(
    lambda x: np.sqrt((x**2).sum() * 78 / len(x))
)

# Resample VIX_close_df to daily frequency, summing up measurements, dividing by the number of measurements, and multiplying by 78

SPX_daily_2014_df = pd.DataFrame(SPX_daily_2014_df)
SPX_daily_2014_df = SPX_daily_2014_df.dropna(subset=['ln(pt/pt-1)']) 
SPX_daily_2014_df = SPX_daily_2014_df[['ln(pt/pt-1)']].rename(columns={'ln(pt/pt-1)': 'RV'})
SPX_daily_2014_df

/tmp/ipykernel_3151/1516254301.py:8: RuntimeWarning: invalid value encountered in scalar divide
  lambda x: np.sqrt((x**2).sum() * 78 / len(x))

                  RV
Date
2014-03-11  0.005030
2014-03-12  0.005201
2014-03-13  0.007031
2014-03-14  0.006866
2014-03-17  0.005269
...              ...
2019-05-24  0.004421
2019-05-28  0.005266
2019-05-29  0.008306
2019-05-30  0.005780
2019-05-31  0.005426

[1315 rows x 1 columns]

In [13]:
SPX_daily_2014_df.sort_index(inplace=True)
SPX_daily_2014_df.index.name = "Date"
SPX_daily_2014_df.to_csv("SPX_daily_2014.csv", index=True)
SPX_daily_2014_df

                  RV
Date
2014-03-11  0.005030
2014-03-12  0.005201
2014-03-13  0.007031
2014-03-14  0.006866
2014-03-17  0.005269
...              ...
2019-05-24  0.004421
2019-05-28  0.005266
2019-05-29  0.008306
2019-05-30  0.005780
2019-05-31  0.005426

[1315 rows x 1 columns]

In [14]:
SPX_daily_2014_df.index = pd.to_datetime(SPX_daily_2014_df.index, infer_datetime_format=True)
SPX_daily_2014_df.sort_index(inplace=True)
SPX_daily_2014_df.to_csv("SPX_daily_2014.csv", index=True)

/tmp/ipykernel_3151/3035855236.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  SPX_daily_2014_df.index = pd.to_datetime(SPX_daily_2014_df.index, infer_datetime_format=True)

In [15]:
SPX_daily_2014_df

                  RV
Date
2014-03-11  0.005030
2014-03-12  0.005201
2014-03-13  0.007031
2014-03-14  0.006866
2014-03-17  0.005269
...              ...
2019-05-24  0.004421
2019-05-28  0.005266
2019-05-29  0.008306
2019-05-30  0.005780
2019-05-31  0.005426

[1315 rows x 1 columns]

In [16]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("SPX_daily_2014.csv")

# Convert the 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Filter the DataFrame to include only dates on or after May 1st, 2014
df_filtered = df[df['Date'] >= '2014-05-01']

# (Optional) Save the filtered DataFrame to a new CSV file
df_filtered.to_csv("SPX_may2014.csv", index=False)

SPX_may2014_df = pd.read_csv("SPX_may2014.csv")
SPX_may2014_df = SPX_may2014_df.iloc[0:1275]
SPX_may2014_df

            Date        RV
0     2014-05-01  0.004199
1     2014-05-02  0.005398
2     2014-05-05  0.004376
3     2014-05-06  0.004478
4     2014-05-07  0.008027
...          ...       ...
1270  2019-05-20  0.006645
1271  2019-05-21  0.003758
1272  2019-05-22  0.004418
1273  2019-05-23  0.006664
1274  2019-05-24  0.004421

[1275 rows x 2 columns]

In [17]:
VIX_2014_df = pd.read_csv("vix_2014_raw.csv")
VIX_2014_df

           Date   Open   High    Low  Close
0     5/24/2019  16.34  16.52  15.52  15.85
1     5/23/2019  15.93  18.05  15.28  16.92
2     5/22/2019  15.06  15.44  14.42  14.75
3     5/21/2019  15.86  16.22  14.79  14.95
4     5/20/2019  15.88  17.63  15.46  16.31
...         ...    ...    ...    ...    ...
1271   5/7/2014  13.64  14.49  13.39  13.40
1272   5/6/2014  13.65  13.90  13.28  13.80
1273   5/5/2014  13.95  14.20  13.08  13.29
1274   5/2/2014  13.15  13.50  12.83  12.91
1275   5/1/2014  13.64  13.75  13.10  13.25

[1276 rows x 5 columns]

In [18]:
VIX_2014_df = VIX_2014_df[['Date', 'Close']]
VIX_2014_df

           Date  Close
0     5/24/2019  15.85
1     5/23/2019  16.92
2     5/22/2019  14.75
3     5/21/2019  14.95
4     5/20/2019  16.31
...         ...    ...
1271   5/7/2014  13.40
1272   5/6/2014  13.80
1273   5/5/2014  13.29
1274   5/2/2014  12.91
1275   5/1/2014  13.25

[1276 rows x 2 columns]

In [19]:
VIX_2014_df.to_csv("VIX_daily_2014_df.csv", index=False)

In [20]:
# Load the newly uploaded CSV file
vix_daily_df = pd.read_csv("VIX_daily_2014_df.csv")

# Convert the 'Date' column to datetime format
vix_daily_df['Date'] = pd.to_datetime(vix_daily_df['Date'])

# Sort the DataFrame by 'Date' in chronological order
vix_daily_df_sorted = vix_daily_df.sort_values(by='Date').reset_index(drop=True)

# Save the sorted DataFrame to a new CSV file
vix_daily_df_sorted.to_csv("VIX_daily_2014_df.csv", index=False)



vix_daily_df_sorted

vix_daily_df_sorted.index = pd.to_datetime(vix_daily_df_sorted.index, infer_datetime_format=True)
vix_daily_df_sorted

/tmp/ipykernel_3151/85963724.py:22: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  vix_daily_df_sorted.index = pd.to_datetime(vix_daily_df_sorted.index, infer_datetime_format=True)

                                    Date  Close
1970-01-01 00:00:00.000000000 2014-05-01  13.25
1970-01-01 00:00:00.000000001 2014-05-02  12.91
1970-01-01 00:00:00.000000002 2014-05-05  13.29
1970-01-01 00:00:00.000000003 2014-05-06  13.80
1970-01-01 00:00:00.000000004 2014-05-07  13.40
...                                  ...    ...
1970-01-01 00:00:00.000001271 2019-05-20  16.31
1970-01-01 00:00:00.000001272 2019-05-21  14.95
1970-01-01 00:00:00.000001273 2019-05-22  14.75
1970-01-01 00:00:00.000001274 2019-05-23  16.92
1970-01-01 00:00:00.000001275 2019-05-24  15.85

[1276 rows x 2 columns]

In [21]:
def_spread_2014_df = pd.read_csv("/work/Default_Spread_test - Sheet2.csv")
def_spread_2014_df.index = pd.to_datetime(def_spread_2014_df.index, infer_datetime_format=True)
def_spread_2014_df = def_spread_2014_df.iloc[0:1322]
def_spread_2014_df

/tmp/ipykernel_3151/2870856963.py:7: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  def_spread_2014_df.index = pd.to_datetime(def_spread_2014_df.index, infer_datetime_format=True)

                                     Date  Default Spread
1970-01-01 00:00:00.000000000  2014-05-01            0.61
1970-01-01 00:00:00.000000001  2014-05-02            0.62
1970-01-01 00:00:00.000000002  2014-05-05            0.62
1970-01-01 00:00:00.000000003  2014-05-06            0.63
1970-01-01 00:00:00.000000004  2014-05-07            0.62
...                                   ...             ...
1970-01-01 00:00:00.000001317  2019-05-20            0.95
1970-01-01 00:00:00.000001318  2019-05-21            0.96
1970-01-01 00:00:00.000001319  2019-05-22            0.97
1970-01-01 00:00:00.000001320  2019-05-23            0.95
1970-01-01 00:00:00.000001321  2019-05-24            0.99

[1322 rows x 2 columns]

In [22]:
SPX_2014_df
SPX_2014_returns = SPX_2014_df[['Date','ln(pt/pt-1)']]
SPX_2014_returns
SPX_2014_returns.to_csv("SPX_2014_returns.csv", index=False)

In [23]:
import pandas as pd
str_2014_df = pd.read_csv("STR_2014.csv")
str_2014_df = str_2014_df[["Date", "ST_Rev"]]
str_2014_df['Date'] = str_2014_df['Date'].astype(str).str.extract(r'(\d{8})$')[0]
str_2014_df['Date'] = pd.to_datetime(str_2014_df['Date'], format='%Y%m%d')

str_2014_df.index = pd.to_datetime(str_2014_df.index, infer_datetime_format=True)
str_2014_df

/tmp/ipykernel_3151/1998369301.py:12: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  str_2014_df.index = pd.to_datetime(str_2014_df.index, infer_datetime_format=True)

                                    Date  ST_Rev
1970-01-01 00:00:00.000000000 2014-05-01    0.74
1970-01-01 00:00:00.000000001 2014-05-02    0.15
1970-01-01 00:00:00.000000002 2014-05-05   -0.21
1970-01-01 00:00:00.000000003 2014-05-06   -0.62
1970-01-01 00:00:00.000000004 2014-05-07   -0.60
...                                  ...     ...
1970-01-01 00:00:00.000001271 2019-05-20   -0.70
1970-01-01 00:00:00.000001272 2019-05-21    0.77
1970-01-01 00:00:00.000001273 2019-05-22   -1.37
1970-01-01 00:00:00.000001274 2019-05-23   -0.89
1970-01-01 00:00:00.000001275 2019-05-24   -0.29

[1276 rows x 2 columns]

In [24]:
mkt_2014_df = pd.read_csv("MKT_2014_2019.csv")
mkt_2014_df = mkt_2014_df[["Date", "mkt"]]
mkt_2014_df

mkt_2014_df['Date'] = pd.to_datetime(mkt_2014_df['Date'])

# Sort the DataFrame by 'Date' in chronological order
mkt_2014_df = mkt_2014_df.sort_values(by='Date').reset_index(drop=True)

mkt_2014_df.index = pd.to_datetime(mkt_2014_df.index, infer_datetime_format=True)
mkt_2014_df

/tmp/ipykernel_3151/1608931653.py:15: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  mkt_2014_df.index = pd.to_datetime(mkt_2014_df.index, infer_datetime_format=True)

                                    Date       mkt
1970-01-01 00:00:00.000000000 2014-05-01       NaN
1970-01-01 00:00:00.000000001 2014-05-02 -0.001349
1970-01-01 00:00:00.000000002 2014-05-05  0.001870
1970-01-01 00:00:00.000000003 2014-05-06 -0.008990
1970-01-01 00:00:00.000000004 2014-05-07  0.005615
...                                  ...       ...
1970-01-01 00:00:00.000001271 2019-05-20 -0.006842
1970-01-01 00:00:00.000001272 2019-05-21  0.008403
1970-01-01 00:00:00.000001273 2019-05-22 -0.002917
1970-01-01 00:00:00.000001274 2019-05-23 -0.012006
1970-01-01 00:00:00.000001275 2019-05-24  0.001262

[1276 rows x 2 columns]

In [25]:
jump_var_df = pd.read_csv("jump_2014_metrics.csv")
jump_var_df = jump_var_df[["Date", "JV"]]
jump_var_df = jump_var_df.iloc[36:1315]
jump_var_df['Date'] = pd.to_datetime(jump_var_df['Date'])
jump_var_df.index = pd.to_datetime(jump_var_df.index, infer_datetime_format=True)
jump_var_df = jump_var_df.iloc[0:1275]
jump_var_df

/tmp/ipykernel_3151/3275573346.py:10: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  jump_var_df.index = pd.to_datetime(jump_var_df.index, infer_datetime_format=True)

                                    Date        JV
1970-01-01 00:00:00.000000036 2014-05-01  0.000000
1970-01-01 00:00:00.000000037 2014-05-02  0.000001
1970-01-01 00:00:00.000000038 2014-05-05  0.000046
1970-01-01 00:00:00.000000039 2014-05-06  0.000006
1970-01-01 00:00:00.000000040 2014-05-07  0.000011
...                                  ...       ...
1970-01-01 00:00:00.000001306 2019-05-20  0.000022
1970-01-01 00:00:00.000001307 2019-05-21  0.000047
1970-01-01 00:00:00.000001308 2019-05-22  0.000007
1970-01-01 00:00:00.000001309 2019-05-23  0.000102
1970-01-01 00:00:00.000001310 2019-05-24  0.000034

[1275 rows x 2 columns]

In [26]:
import pandas as pd
dpr_2014_df = pd.read_csv("DPR_2014.csv")


dpr_2014_df['Date'] = pd.to_datetime(dpr_2014_df['Date'])

# Sort the DataFrame by 'Date' in chronological order
dpr_2014_df = dpr_2014_df.sort_values(by='Date').reset_index(drop=True)

dpr_2014_df.index = pd.to_datetime(dpr_2014_df.index, infer_datetime_format=True)
dpr_2014_df

/tmp/ipykernel_3151/985062591.py:15: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  dpr_2014_df.index = pd.to_datetime(dpr_2014_df.index, infer_datetime_format=True)

,Date,SPX Index - Dividend 12 Month Yld - Gross
1970-01-01 00:00:00.000000000,2014-05-01,1.9482
1970-01-01 00:00:00.000000001,2014-05-02,1.9508
1970-01-01 00:00:00.000000002,2014-05-05,1.9467
1970-01-01 00:00:00.000000003,2014-05-06,1.9647
1970-01-01 00:00:00.000000004,2014-05-07,1.9591
...,...,...
1970-01-01 00:00:00.000001271,2019-05-20,1.9612
1970-01-01 00:00:00.000001272,2019-05-21,1.9449
1970-01-01 00:00:00.000001273,2019-05-22,1.9505
1970-01-01 00:00:00.000001274,2019-05-23,1.9748
1970-01-01 00:00:00.000001275,2019-05-24,1.9733

In [27]:
for df in [SPX_may2014_df, vix_daily_df_sorted, str_2014_df, mkt_2014_df, jump_var_df, dpr_2014_df, def_spread_2014_df]:
    df['Date'] = pd.to_datetime(df['Date'])
    df.set_index('Date', inplace=True)

merged_2014 = SPX_may2014_df.join(
    [vix_daily_df_sorted, str_2014_df, mkt_2014_df, jump_var_df, dpr_2014_df, def_spread_2014_df],
    how='left'
)
merged_2014

,RV,Close,ST_Rev,mkt,JV,SPX Index - Dividend 12 Month Yld - Gross,Default Spread
Date,,,,,,,
2014-05-01,0.004199,13.25,0.74,NaN,0.000000,1.9482,0.61
2014-05-02,0.005398,12.91,0.15,-0.001349,0.000001,1.9508,0.62
2014-05-05,0.004376,13.29,-0.21,0.001870,0.000046,1.9467,0.62
2014-05-06,0.004478,13.80,-0.62,-0.008990,0.000006,1.9647,0.63
2014-05-07,0.008027,13.40,-0.60,0.005615,0.000011,1.9591,0.62
...,...,...,...,...,...,...,...
2019-05-20,0.006645,16.31,-0.70,-0.006842,0.000022,1.9612,0.95
2019-05-21,0.003758,14.95,0.77,0.008403,0.000047,1.9449,0.96
2019-05-22,0.004418,14.75,-1.37,-0.002917,0.000007,1.9505,0.97
2019-05-23,0.006664,16.92,-0.89,-0.012006,0.000102,1.9748,0.95
2019-05-24,0.004421,15.85,-0.29,0.001262,0.000034,1.9733,0.99

In [28]:
merged_2014.columns = ['SPX','VIX', 'STR', 'MKT', 'Jump', 'DPR', 'DS']

In [29]:
merged_2014 = merged_2014[merged_2014.index <= pd.to_datetime('2025-04-30', format='%Y-%m-%d')]
print(merged_2014.index.name)

Date

In [30]:
merged_2014['RV_day'] = merged_2014['SPX'].shift(1)
merged_2014['RV_week'] = merged_2014['SPX'].shift(1).rolling(window=5).mean()
merged_2014['RV_month'] = merged_2014['SPX'].shift(1).rolling(window=22).mean()
merged_2014

,SPX,VIX,STR,MKT,Jump,DPR,DS,RV_day,RV_week,RV_month
Date,,,,,,,,,,
2014-05-01,0.004199,13.25,0.74,NaN,0.000000,1.9482,0.61,NaN,NaN,NaN
2014-05-02,0.005398,12.91,0.15,-0.001349,0.000001,1.9508,0.62,0.004199,NaN,NaN
2014-05-05,0.004376,13.29,-0.21,0.001870,0.000046,1.9467,0.62,0.005398,NaN,NaN
2014-05-06,0.004478,13.80,-0.62,-0.008990,0.000006,1.9647,0.63,0.004376,NaN,NaN
2014-05-07,0.008027,13.40,-0.60,0.005615,0.000011,1.9591,0.62,0.004478,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2019-05-20,0.006645,16.31,-0.70,-0.006842,0.000022,1.9612,0.95,0.007277,0.007221,0.005715
2019-05-21,0.003758,14.95,0.77,0.008403,0.000047,1.9449,0.96,0.006645,0.006649,0.005830
2019-05-22,0.004418,14.75,-1.37,-0.002917,0.000007,1.9505,0.97,0.003758,0.005979,0.005839
2019-05-23,0.006664,16.92,-0.89,-0.012006,0.000102,1.9748,0.95,0.004418,0.005427,0.005922
2019-05-24,0.004421,15.85,-0.29,0.001262,0.000034,1.9733,0.99,0.006664,0.005752,0.006060

In [31]:
y_2014 = merged_2014['SPX']
X_2014 = merged_2014.drop(columns=['SPX'])

In [32]:
X_2014 = X_2014.interpolate(method='linear', limit_direction='both')
X_2014

,VIX,STR,MKT,Jump,DPR,DS,RV_day,RV_week,RV_month
Date,,,,,,,,,
2014-05-01,13.25,0.74,-0.001349,0.000000,1.9482,0.61,0.004199,0.005296,0.004039
2014-05-02,12.91,0.15,-0.001349,0.000001,1.9508,0.62,0.004199,0.005296,0.004039
2014-05-05,13.29,-0.21,0.001870,0.000046,1.9467,0.62,0.005398,0.005296,0.004039
2014-05-06,13.80,-0.62,-0.008990,0.000006,1.9647,0.63,0.004376,0.005296,0.004039
2014-05-07,13.40,-0.60,0.005615,0.000011,1.9591,0.62,0.004478,0.005296,0.004039
...,...,...,...,...,...,...,...,...,...
2019-05-20,16.31,-0.70,-0.006842,0.000022,1.9612,0.95,0.007277,0.007221,0.005715
2019-05-21,14.95,0.77,0.008403,0.000047,1.9449,0.96,0.006645,0.006649,0.005830
2019-05-22,14.75,-1.37,-0.002917,0.000007,1.9505,0.97,0.003758,0.005979,0.005839
2019-05-23,16.92,-0.89,-0.012006,0.000102,1.9748,0.95,0.004418,0.005427,0.005922
2019-05-24,15.85,-0.29,0.001262,0.000034,1.9733,0.99,0.006664,0.005752,0.006060

In [33]:
X_2014.to_csv("X_2014.csv")
y_2014.to_csv("y_2014.csv")

In [34]:
import pandas as pd
import joblib

# Load csv file as dataframe
df_X = pd.read_csv("X_2014.csv", index_col=0)
df_y = pd.read_csv("y_2014.csv", index_col=0)

# Load scaler X
scaler1 = joblib.load('X_scaler.pkl')
df_X_scaled = pd.DataFrame(
    scaler1.transform(df_X),
    columns=df_X.columns,
    index=df_X.index
)
# Load scaler y 
scaler2 = joblib.load('y_scaler.pkl')
df_y_scaled = pd.DataFrame(
    scaler2.transform(df_y),
    columns=df_y.columns,
    index=df_y.index
)

df_y_scaled

/root/venv/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator StandardScaler from version 1.7.0 when using version 1.1.3. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

                 SPX
Date
2014-05-01 -0.697904
2014-05-02 -0.550572
2014-05-05 -0.676188
2014-05-06 -0.663579
2014-05-07 -0.227599
...              ...
2019-05-20 -0.397477
2019-05-21 -0.752137
2019-05-22 -0.671069
2019-05-23 -0.395037
2019-05-24 -0.670672

[1275 rows x 1 columns]

In [35]:
df_y_scaled

                 SPX
Date
2014-05-01 -0.697904
2014-05-02 -0.550572
2014-05-05 -0.676188
2014-05-06 -0.663579
2014-05-07 -0.227599
...              ...
2019-05-20 -0.397477
2019-05-21 -0.752137
2019-05-22 -0.671069
2019-05-23 -0.395037
2019-05-24 -0.670672

[1275 rows x 1 columns]

In [36]:
df_X_scaled.to_csv("X_2014_scaled.csv")
df_y_scaled.to_csv("y_2014_scaled.csv")

In [37]:
df = pd.read_csv("AX_DATA.csv", index_col=0)
kurtosis = pd.read_csv("skew_kurtosis.csv", index_col=0)

In [38]:
kurtosis

            realized_skew  realized_kurt
date
2014-03-11      -0.207492       2.881472
2014-03-12      -2.917930      19.694813
2014-03-13       0.141971       3.309818
2014-03-14       0.543074       4.060279
2014-03-17       4.018353      26.733037
...                   ...            ...
2025-05-20      -1.001584       5.950277
2025-05-21      -1.156579       6.900728
2025-05-22      -0.705464       4.069532
2025-05-23      -4.723850      35.024769
2025-05-27       7.350861      61.498227

[2820 rows x 2 columns]

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=c491ba08-7b0b-4e77-bbce-46de4cee5dd0' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>